<a href="https://colab.research.google.com/github/GandhiniP/demo/blob/main/groupdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_excel("FDP17data.xlsx")
df

,Student_ID,Student_Name,Department,Class,Attendance_Percent,Marks,Study_Hours_Per_Day,Result
0,STU001,Arun,CSE,A,90,85,4,Pass
1,STU002,Bala,ECE,A,82,72,3,Pass
2,STU003,Citra,CSE,A,95,91,5,Pass
3,STU004,Deepa,ECE,A,76,48,2,Fail
4,STU005,Elango,IT,A,88,79,4,Pass
5,STU006,Fathima,IT,A,92,88,5,Pass
6,STU007,Gokul,CSE,A,68,55,2,Fail
7,STU008,Hari,ECE,A,85,82,3,Pass
8,STU009,Isha,IT,A,97,95,6,Pass
9,STU010,John,ECE,A,73,61,2,Pass
10,STU011,Kavi,CSE,B,89,82,4,Pass
11,STU012,Latha,IT,B,94,90,5,Pass
12,STU013,Manoj,CSE,B,78,68,3,Pass
13,STU014,Nila,ECE,B,80,74,3,Pass
14,STU015,Oviya,IT,B,86,77,4,Pass
15,STU016,Pranav,CSE,B,72,58,2,Fail
16,STU017,Quincy,ECE,B,91,87,5,Pass
17,STU018,Ravi,IT,B,84,69,3,Pass
18,STU019,Sneha,CSE,B,96,93,6,Pass
19,STU020,Tarun,ECE,B,77,64,2,Pass
20,STU021,Uma,IT,C,90,84,4,Pass
21,STU022,Vikram,CSE,C,83,76,3,Pass
22,STU023,Wafa,ECE,C,69,52,2,Fail
23,STU024,Xavier,IT,C,98,96,6,Pass
24,STU025,Yamini,CSE,C,87,81,4,Pass
25,STU026,Zahir,ECE,C,88,79,4,Pass
26,STU027,Aarthi,IT,C,75,59,2,Fail
27,STU028,Bharat,CSE,C,92,89,5,Pass
28,STU029,Charu,ECE,C,84,71,3,Pass
29,STU030,Dinesh,IT,C,81,66,3,Pass

In [ ]:
df.head()
print(df.shape)
df.columns

(30, 8)

Index(['Student_ID', 'Student_Name', 'Department', 'Class',
       'Attendance_Percent', 'Marks', 'Study_Hours_Per_Day', 'Result'],
      dtype='object')

In [ ]:
print(df.groupby("Department")["Marks"].max())
print(df.groupby("Department")["Marks"].min())

Department
CSE    93
ECE    87
IT     96
Name: Marks, dtype: int64
Department
CSE    55
ECE    48
IT     59
Name: Marks, dtype: int64

In [ ]:

print(df.groupby("Department")["Marks"].agg(["count","max","min","median"]))

            count  max  min  median
Department
CSE            10   93   55    81.5
ECE            10   87   48    71.5
IT             10   96   59    81.5

In [ ]:
print(df.groupby("Department")[["Marks","Attendance_Percent"]].mean())

            Marks  Attendance_Percent
Department
CSE          77.8                85.0
ECE          69.0                80.5
IT           80.3                88.5

In [ ]:
pd.pivot_table(
    df,
    index="Department",
    values="Marks",
    columns="Class",
    aggfunc="mean"
)

Class               A          B          C
Department
CSE         77.000000  75.250000  82.000000
ECE         65.750000  75.000000  67.333333
IT          87.333333  78.666667  76.250000

In [ ]:
pd.crosstab(df["Department"],df["Result"])

Result      Fail  Pass
Department
CSE            2     8
ECE            2     8
IT             1     9